//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManufuctredCompanyPortofolio.DAL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ManufuctredCompanyPortofolio.DAL.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string btn_Delete {
            get {
                return ResourceManager.GetString("btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string btn_Edit {
            get {
                return ResourceManager.GetString("btn_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string btn_New {
            get {
                return ResourceManager.GetString("btn_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btn_Save {
            get {
                return ResourceManager.GetString("btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string lbl_Add {
            get {
                return ResourceManager.GetString("lbl_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string lbl_Address {
            get {
                return ResourceManager.GetString("lbl_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Row.
        /// </summary>
        public static string lbl_AddRow {
            get {
                return ResourceManager.GetString("lbl_AddRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Name.
        /// </summary>
        public static string lbl_ArName {
            get {
                return ResourceManager.GetString("lbl_ArName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Forward.
        /// </summary>
        public static string lbl_backForward {
            get {
                return ResourceManager.GetString("lbl_backForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string lbl_Choose {
            get {
                return ResourceManager.GetString("lbl_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string lbl_Close {
            get {
                return ResourceManager.GetString("lbl_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string lbl_Code {
            get {
                return ResourceManager.GetString("lbl_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Length Must Between 5 And 30 Chars.
        /// </summary>
        public static string lbl_CodeMustBeBetwwen30And3 {
            get {
                return ResourceManager.GetString("lbl_CodeMustBeBetwwen30And3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Branches.
        /// </summary>
        public static string lbl_CompanyBranches {
            get {
                return ResourceManager.GetString("lbl_CompanyBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communications Methods.
        /// </summary>
        public static string lbl_CompanyCommunications {
            get {
                return ResourceManager.GetString("lbl_CompanyCommunications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Data.
        /// </summary>
        public static string lbl_CompanyData {
            get {
                return ResourceManager.GetString("lbl_CompanyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to confirm.
        /// </summary>
        public static string lbl_Confirm {
            get {
                return ResourceManager.GetString("lbl_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string lbl_Country {
            get {
                return ResourceManager.GetString("lbl_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current  Address.
        /// </summary>
        public static string lbl_CurrentAddress {
            get {
                return ResourceManager.GetString("lbl_CurrentAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string lbl_Delete {
            get {
                return ResourceManager.GetString("lbl_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Row.
        /// </summary>
        public static string lbl_DeleteRow {
            get {
                return ResourceManager.GetString("lbl_DeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string lbl_Department {
            get {
                return ResourceManager.GetString("lbl_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string lbl_Details {
            get {
                return ResourceManager.GetString("lbl_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string lbl_Email {
            get {
                return ResourceManager.GetString("lbl_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string lbl_Employees {
            get {
                return ResourceManager.GetString("lbl_Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty String.
        /// </summary>
        public static string lbl_EmptyString {
            get {
                return ResourceManager.GetString("lbl_EmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name.
        /// </summary>
        public static string lbl_EnName {
            get {
                return ResourceManager.GetString("lbl_EnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string lbl_Fax {
            get {
                return ResourceManager.GetString("lbl_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ground Tel.
        /// </summary>
        public static string lbl_GroundTel {
            get {
                return ResourceManager.GetString("lbl_GroundTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string lbl_Image {
            get {
                return ResourceManager.GetString("lbl_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Invalid.
        /// </summary>
        public static string lbl_InvalidMail {
            get {
                return ResourceManager.GetString("lbl_InvalidMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string lbl_IsActive {
            get {
                return ResourceManager.GetString("lbl_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufctred Companies.
        /// </summary>
        public static string lbl_ManufctresCompanies {
            get {
                return ResourceManager.GetString("lbl_ManufctresCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible People For Branches.
        /// </summary>
        public static string lbl_ManufctresCompaniesBranchesResponsiblePerson {
            get {
                return ResourceManager.GetString("lbl_ManufctresCompaniesBranchesResponsiblePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Length Of Passowrd Shoud Be Five.
        /// </summary>
        public static string lbl_MinLengthMustBeFive {
            get {
                return ResourceManager.GetString("lbl_MinLengthMustBeFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string lbl_Mobile {
            get {
                return ResourceManager.GetString("lbl_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lbl_Name {
            get {
                return ResourceManager.GetString("lbl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There Is No Data.
        /// </summary>
        public static string lbl_NoData {
            get {
                return ResourceManager.GetString("lbl_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No File Choosen.
        /// </summary>
        public static string lbl_NoFileChoosen {
            get {
                return ResourceManager.GetString("lbl_NoFileChoosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string lbl_OK {
            get {
                return ResourceManager.GetString("lbl_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Succeeded.
        /// </summary>
        public static string lbl_operationSucceded {
            get {
                return ResourceManager.GetString("lbl_operationSucceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Dont Match.
        /// </summary>
        public static string lbl_PasswordDontMatch {
            get {
                return ResourceManager.GetString("lbl_PasswordDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to portfolio Project.
        /// </summary>
        public static string lbl_portfolioProject {
            get {
                return ResourceManager.GetString("lbl_portfolioProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Is Repeated.
        /// </summary>
        public static string lbl_RepeatedCode {
            get {
                return ResourceManager.GetString("lbl_RepeatedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Is Required.
        /// </summary>
        public static string lbl_RequiredEmail {
            get {
                return ResourceManager.GetString("lbl_RequiredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Field Is Required.
        /// </summary>
        public static string lbl_RequiredMessage {
            get {
                return ResourceManager.GetString("lbl_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Is Required.
        /// </summary>
        public static string lbl_RequiredPassword {
            get {
                return ResourceManager.GetString("lbl_RequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions And Terms Should Be Agreed.
        /// </summary>
        public static string lbl_RequiredTermsAndConditions {
            get {
                return ResourceManager.GetString("lbl_RequiredTermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string lbl_Search {
            get {
                return ResourceManager.GetString("lbl_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignOut.
        /// </summary>
        public static string lbl_SignOut {
            get {
                return ResourceManager.GetString("lbl_SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Should Be Number.
        /// </summary>
        public static string lbl_ThisIsMustBeumber {
            get {
                return ResourceManager.GetString("lbl_ThisIsMustBeumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string lbl_Warining {
            get {
                return ResourceManager.GetString("lbl_Warining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string lblComanyName {
            get {
                return ResourceManager.GetString("lblComanyName", resourceCulture);
            }
        }
    }
}
